version: '3'

services:
  issue-creator:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
